version: '3'

services:

  # assumes imgsrv-sample-data has been checked out next to "imgsrv"
  imgsrv:
    build: .
    image: hathitrust-imgsrv
    volumes:
      - .:/htapps/babel/imgsrv
      - "../imgsrv-sample-data/sdr1:/sdr1"
      - "../imgsrv-sample-data/etc:/htapps/babel/etc"
      - "../imgsrv-sample-data/watermarks:/htapps/babel/watermarks"
      - "../imgsrv-sample-data:/tmp/imgsrv-sample-data"
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=roger
      - MARIADB_USER=ht_web
      - REMOTE_ADDR=127.0.0.1
      - HTTP_HOST=127.0.0.1
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog
    ports:
      - "31028:31028"
    command: bash -c "/htapps/babel/imgsrv/bin/startup_imgsrv"

  solr-sdr-catalog:
    image: ghcr.io/hathitrust/catalog-solr-sample
    ports:
      - "9033:9033"

  mysql-sdr:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'babel'
    ports:
      - 3306:3006

  nginx:
    image: hathitrust-imgsrv
    ports:
      - "8888:8080"
    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - .:/htapps/babel/imgsrv
      - "../imgsrv-sample-data/sdr1:/sdr1"
      - "../imgsrv-sample-data/etc:/htapps/babel/etc"
      - "../imgsrv-sample-data/watermarks:/htapps/babel/watermarks"
      - "../imgsrv-sample-data:/tmp/imgsrv-sample-data"
    depends_on:
      - imgsrv
      - mysql-sdr
      - solr-sdr-catalog
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=roger
      - MARIADB_USER=ht_web
    command: bash -c "/htapps/babel/imgsrv/docker/nginx-entrypoint.sh"

volumes:
  # sdr1:
  data_db:
