version: '3'

services:

  # assumes imgsrv-sample-data has been checked out next to "imgsrv"
  imgsrv:
    build: .
    image: hathitrust-imgsrv
    volumes:
      - .:/htapps/babel/imgsrv
      - "../imgsrv-sample-data/sdr1:/sdr1"
      - "../imgsrv-sample-data/etc:/htapps/babel/etc"
      - "../imgsrv-sample-data/watermarks:/htapps/babel/watermarks"
      - "../imgsrv-sample-data:/tmp/imgsrv-sample-data"
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=docker
      - REMOTE_ADDR=127.0.0.1
      - HTTP_HOST=127.0.0.1
    depends_on:
      - mariadb
      - solr-sdr-catalog
    ports:
      - "31028:31028"
    command: bash -c "/htapps/babel/imgsrv/bin/startup_imgsrv"

  solr-sdr-catalog:
    image: ghcr.io/hathitrust/catalog-solr-sample
    ports:
      - "9033:9033"

  mariadb:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    ports:
      - 3306:3006

  apache-cgi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.apache
    image: hathitrust-imsgsrv-apache
    ports:
      - "8888:80"
    volumes:
      - .:/htapps/babel/imgsrv
      - ./docker/sites-available:/etc/apache2/sites-available
      - "../imgsrv-sample-data/sdr1:/sdr1"
      - "../imgsrv-sample-data/etc:/htapps/babel/etc"
      - "../imgsrv-sample-data/watermarks:/htapps/babel/watermarks"
      - "../imgsrv-sample-data:/tmp/imgsrv-sample-data"
    depends_on:
      - imgsrv
      - mariadb
      - solr-sdr-catalog
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=docker
    command: bash -c "/htapps/babel/imgsrv/docker/bin/apache.sh"

volumes:
  # sdr1:
  data_db:
