FROM nginx


RUN apt-get update && apt-get install -y spawn-fcgi fcgiwrap \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 80

STOPSIGNAL SIGTERM

COPY docker/nginx-entrypoint.sh /
RUN chmod +x /nginx-entrypoint.sh
ENTRYPOINT ["/nginx-entrypoint.sh"]